from pathlib import Path
from typing import List, Tuple

from app.config.settings import settings
from app.models.schemas import BDDScenario, StepDefinition
from app.utils.logger import get_logger

logger = get_logger(__name__)


class BDDService:
    def parse_scenarios(self, raw: dict) -> Tuple[str, List[BDDScenario]]:
        feature_name = raw.get("feature_name", "Application Feature")
        scenarios: List[BDDScenario] = []
        for item in raw.get("scenarios", []):
            scenarios.append(
                BDDScenario(
                    feature=feature_name,
                    scenario_name=item.get("scenario_name", ""),
                    given=item.get("given", []),
                    when=item.get("when", []),
                    then=item.get("then", []),
                    tags=item.get("tags", []),
                )
            )
        return feature_name, scenarios

    def parse_step_definitions(self, raw: dict) -> List[StepDefinition]:
        return [
            StepDefinition(
                step_text=item.get("step_text", ""),
                step_type=item.get("step_type", "Given"),
                code=item.get("code", ""),
                language=item.get("language", "python"),
            )
            for item in raw.get("step_definitions", [])
        ]

    def save_feature_file(
        self,
        feature_name: str,
        scenarios: List[BDDScenario],
        jira_id: str,
    ) -> str:
        path = Path(settings.bdd_path) / f"{jira_id}.feature"
        path.parent.mkdir(parents=True, exist_ok=True)

        lines: List[str] = [f"Feature: {feature_name}", ""]
        for scenario in scenarios:
            if scenario.tags:
                lines.append("  " + " ".join(scenario.tags))
            lines.append(f"  Scenario: {scenario.scenario_name}")
            for step in scenario.given:
                lines.append(f"    Given {step}")
            for i, step in enumerate(scenario.when):
                keyword = "When" if i == 0 else "And"
                lines.append(f"    {keyword} {step}")
            for i, step in enumerate(scenario.then):
                keyword = "Then" if i == 0 else "And"
                lines.append(f"    {keyword} {step}")
            lines.append("")

        path.write_text("\n".join(lines), encoding="utf-8")
        logger.info(f"Feature file → {path}")
        return str(path)

    def save_step_definitions(
        self,
        step_definitions: List[StepDefinition],
        jira_id: str,
    ) -> str:
        path = Path(settings.bdd_path) / f"{jira_id}_steps.py"
        path.parent.mkdir(parents=True, exist_ok=True)

        header = [
            "# Auto-generated pytest-bdd step definitions",
            f"# Ticket: {jira_id}",
            "# Generated by QA Agent Platform",
            "# Target: playwright_project/tests/step_defs/",
            "#",
            "# Usage:",
            "#   pytest tests/step_defs/ -m ui -v",
            "#   pytest tests/step_defs/ -m api -v",
            "",
            "from pathlib import Path",
            "",
            "from pytest_bdd import given, when, then, parsers, scenarios",
            "from playwright.sync_api import Page",
            "",
        ]
        body = []
        for sd in step_definitions:
            body.append(sd.code)
            body.append("")

        path.write_text("\n".join(header + body), encoding="utf-8")
        logger.info(f"pytest-bdd step definitions file → {path}")
        return str(path)


bdd_service = BDDService()
